# -*- coding: utf-8 -*-
"""zomato_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqagvBGBOTss8vu7EH3019-VV_WP-BMA
"""

#importing all libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

#loading csv file
df = pd.read_csv('zomato.csv')
df.head()

df.info()
df.isnull().sum()

# Remove duplicates
df = df.drop_duplicates()

# Clean ratings
df['rate'] = df['rate'].astype(str).str.replace('/5', '')
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

# Clean cost column
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).str.replace(',', '')
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')

# Drop missing ratings
df = df.dropna(subset=['rate'])

#Top Rated Cuisines
df.groupby('cuisines')['rate'].mean().sort_values(ascending=False).head(10)

#Top Locations
df['location'].value_counts().head(10)

#Price vs Rating
sns.scatterplot(x='approx_cost(for two people)', y='rate', data=df)
plt.show()

#Visualizations
#Heatmap
corr = df[['rate', 'approx_cost(for two people)']].corr()
sns.heatmap(corr, annot=True)
plt.show()

#Bar Chart
df['cuisines'].value_counts().head(10).plot(kind='bar')
plt.show()

#WordCloud
text = " ".join(df['cuisines'].dropna())

wordcloud = WordCloud(width=800, height=400).generate(text)

plt.imshow(wordcloud)
plt.axis('off')
plt.show()

"""**Insights:**


**1.Most popular cuisines are:**

---
Healthy Food, Salad, Mediterranean
(4.900000)
    
Continental, North Indian, Italian, South Indian, Finger Food
(4.900000)

Asian, Chinese, Thai, Momos
(4.900000)
    
Asian, Mediterranean, North Indian, BBQ
(4.800000)
    
North Indian, European, Mediterranean, BBQ
(4.800000)

Continental, North Indian, Chinese, European, BBQ, Finger Food, Asian
(4.800000)    

European, Mediterranean, North Indian, BBQ
(4.764286)
    
American, Tex-Mex, Burger, BBQ, Mexican
(4.733333)
    
Continental, European, BBQ, Chinese, Asian
(4.700000)
    
Chinese, American, Continental, Italian, North Indian
(4.700000)

---



**2.Certain locations have more restaurants:**



---



BTM	2445

Koramangala 5th Block	1596

Indiranagar	1582

HSR	1562

Whitefield	1482

Marathahalli	1358

JP Nagar	1216

Jayanagar	1189

Bellandur	942

Bannerghatta Road

---



3.Ratings are not always dependent on price

---


4.Some low-cost restaurants have high ratings

**Recommendations**

* Focus on promoting high-rated and affordable restaurants to attract more customers.

* Partner with restaurants offering popular cuisines like North Indian, Chinese, and South Indian.

* Increase marketing efforts in high-density locations such as BTM, Koramangala, and Indiranagar.

* Highlight customer reviews and ratings to build trust and improve user decision-making.

* Provide visibility to underrated restaurants with good ratings to encourage fair competition.

---
"""

